// Generated by min_text_size --emit-header against res/font/cmu_serif_roman.ttf.
// pixelCriterion=0.5, rasterEmPx=512. thinnestStrokeEm=0.025391.
#pragma once
constexpr float kMinReadableTextSizePx = 19.6923f;
